### ISSUE TITLE
Using cloudera distribution

### ISSUE THREAD

**Issue by Fkawala** [whym/wikihadoop#8]
Hello, 

It seems that the cloudera's team has back-ported (since cdh3u1) the feature enabling hadoop to stream Bz2 files. However in hadoop 0.20 the function "isDirectory" (use at line 155 in StreamWikiDumpInputFormat.java) is still named "isdir".

How can I do to build a an independent jar (as proposed in the download section) without depending on the hadoop 0.21 source code, so that I would be able to test wikihadoop on cloudera ? as a beginner in the domain I can find an answer by myself, may be it is dumb question ?

Thanks a lot,
François.

**Comment by Fkawala** [comment]
Hello, 

I've managed to "backport" the Wikihadoop input format in order to use it on a cloudera 3 update 1 (cdh3u1) (aka. hadoop 0.20.2). Should I open a fork and share it ? 

François

**Comment by whym** [comment]
Hi,

Please do share it!  And then I will be happy to see if I can merge it.

Occasionally I have simplified the build procedure with maven.
https://github.com/whym/wikihadoop/tree/maven
It might help us in merging.

Thanks,
Yusuke

**Comment by Fkawala** [comment]
Hello, 

The fork I've done is now available at : https://github.com/Fkawala/wikihadoop
I hope it could help.

Regards,
François.

**Comment by whym** [comment]
Thank you very much, François!

I merged it with the maven branch and made another branch for cdhu1.
https://github.com/whym/wikihadoop/tree/cdhu1

-Yusuke
